services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./app
    restart: always
    ports:
      - "3009:3009"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/app
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./app:/app
      - /app/node_modules
    command: npm run start:dev

volumes:
  postgres_data:
