version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: study_node_app
    volumes:
      - ./app:/usr/src/app  # Синхронізація вашого коду з контейнером
    ports:
      - "3000:3000"         # Порт для API
      - "3001:3001"         # Порт для WebSockets
    depends_on:
      - postgres
      - redis
    environment:
      # Зверніть увагу: хост бази даних - це ім'я сервісу "postgres", а не localhost
      - DATABASE_URL=postgresql://student:study_password@postgres:5432/study_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  postgres:
    image: postgres:15-alpine
    container_name: study_postgres
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: study_password
      POSTGRES_DB: study_db
    ports:
      - "5433:5432" # 5433 на вашому ПК, 5432 всередині контейнера
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: study_redis
    restart: always
    ports:
      - "6380:6379" # 6380 на вашому ПК, 6379 всередині контейнера
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
