version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: study_node_app
    ports:
      - "3009:3009"
    volumes:
      - ./app/storage:/usr/src/app/storage
