// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"]!,
  },
});

// import 'dotenv/config';
// import path from 'path';
// import { defineConfig } from 'prisma/config';

// export default defineConfig({
//   views: { path: path.join('prisma', 'views') },
//   typedSql: { path: path.join('prisma', 'queries') },
//   schema: path.join('prisma', 'schema'),
//   migrations: {
//     path: path.join('prisma', 'migrations'),
//     seed: 'ts-node --transpile-only prisma/seed/seed.ts',
//   },
// });