export const ERROR_MESSAGES = {
  FILE_NOT_FOUND: 'File not found',
  QUOTA_EXCEEDED: 'Quota exceeded',
  INVALID_FILE_ID: 'Invalid fileId',
  INVALID_QUOTA: 'Invalid quota',
};

export const ERROR_CODES = {
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  INVALID_FILE_ID: 'INVALID_FILE_ID',
  INVALID_QUOTA: 'INVALID_QUOTA',
};
